### ISSUE TITLE
Conflict with FancyMenu

### ISSUE THREAD

**Issue by epicyeeto** [Exploding-Creeper/SimpleSplashScreen#2]
so i am trying to make a custom splash screen using your mod but a problem but there is nothing showing up
![image](https://user-images.githubusercontent.com/73504007/129273287-07899f9e-5377-4699-9af6-8d15a662983f.png)
that is how my config looks like

and Idk but i think the problem is that i have fancymenu installed

**Comment by hypherionmc** [comment]
The config looks okay. FancyMenu could be a problem, but the only reason I can think of it interfering is if you have the darkLoadingScreen option enabled in fancy menu. 

What version are you using? Then I can try to test it on my side

**Comment by hypherionmc** [comment]
Actually no come to think of it, I use fancy menu in my own modpack along with this mod and it works fine, so I don't think that's the issue. Just make sure you have darkLoadingScreen disabled in FancyMenu

**Comment by epicyeeto** [comment]
yes i disabled darkloadingscreen
![image](https://user-images.githubusercontent.com/73504007/129273902-9ab41a29-7a2a-45b8-a0cb-e7e63783903c.png)

**Comment by hypherionmc** [comment]
Okay so I can confirm the current version of fancy menu appears to conflict with this mod. I'll work on a fix for it

**Comment by epicyeeto** [comment]
ok, thank you for responding!

**Comment by hypherionmc** [comment]
Okay, so for now it seems there is nothing I can do from my side to make it compatible. I will have to speak to the dev of fancy menu. For now, if you still want to use my mod, use a version of fancy menu pre 2.2.1

**Comment by epicyeeto** [comment]
ok
